//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMBIO_MONEDA
    {
        public decimal ID_MONEDA { get; set; }
        public float VALOR_CAMBIO { get; set; }
        public int MONEDA_CAMBIO { get; set; }
    
        public virtual MONEDA MONEDA { get; set; }
    }
}
