//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_EXTRAS
    {
        public decimal ID_DATOS_EXTRAS { get; set; }
        public Nullable<int> ID_AGENTE { get; set; }
    
        public virtual AGENTES AGENTES { get; set; }
    }
}
