//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class HITOS_NO_LABORALES
    {
        public decimal ID_HITOS { get; set; }
        public string RUT_EMPRESA_PROV { get; set; }
        public string DESCRIPCION_HITONL { get; set; }
        public Nullable<System.DateTime> FECHA_INICO_HITONL { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_HITONL { get; set; }
        public Nullable<System.DateTime> HORA_INICIO_HITONL { get; set; }
        public Nullable<System.DateTime> HORA_TERMNO_HITONL { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
