//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO_EMPRESA()
        {
            this.SLA = new HashSet<SLA>();
            this.TKT = new HashSet<TKT>();
        }
    
        public Nullable<decimal> ID_SERV { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
        public decimal ID_SERVI_EMP { get; set; }
    
        public virtual EMPRESA_CLI EMPRESA_CLI { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLA> SLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT> TKT { get; set; }
    }
}
