//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_FINAL
    {
        public decimal ID_USUFINAL { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
        public Nullable<decimal> ID_LOGIN { get; set; }
        public byte VIP { get; set; }
    
        public virtual EMPRESA_CLI EMPRESA_CLI { get; set; }
        public virtual LOGIN LOGIN { get; set; }
    }
}
