//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.SERVICIO_EMPRESA = new HashSet<SERVICIO_EMPRESA>();
        }
    
        public decimal ID_SERV { get; set; }
        public Nullable<decimal> ID_EMPRESA_PROV { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
    
        public virtual EMPRESA_Prov EMPRESA_Prov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_EMPRESA> SERVICIO_EMPRESA { get; set; }
    }
}
