//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENTES()
        {
            this.DATOS_EXTRAS = new HashSet<DATOS_EXTRAS>();
            this.HIJOS = new HashSet<HIJOS>();
        }
    
        public string RUT_EMPRESA_PROV { get; set; }
        public int ID_AGENTE { get; set; }
        public Nullable<decimal> ID_LOGIN { get; set; }
        public Nullable<decimal> ID_COMUNA { get; set; }
        public Nullable<decimal> ID_AREA { get; set; }
        public string NOMBRE_AGENTE { get; set; }
        public string APELLIDOP_AGENTE { get; set; }
        public string APELLIDOM_AGENTE { get; set; }
        public string EMAIL_AGENTE { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual COMUNAS COMUNAS { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATOS_EXTRAS> DATOS_EXTRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIJOS> HIJOS { get; set; }
    }
}
