//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class METADATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public METADATA()
        {
            this.DISTRITOS = new HashSet<DISTRITOS>();
        }
    
        public decimal FECHA_META { get; set; }
        public string VALOR_META { get; set; }
        public Nullable<decimal> ID_TIPO_META { get; set; }
    
        public virtual TIPOS_METADTA TIPOS_METADTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRITOS> DISTRITOS { get; set; }
    }
}
