//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKT()
        {
            this.HISTORIA = new HashSet<HISTORIA>();
        }
    
        public decimal ID_TKT { get; set; }
        public Nullable<decimal> ID_URGENCIA { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public Nullable<decimal> ID_IMPACTO { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<decimal> ID_LOGIN { get; set; }
        public Nullable<decimal> ID_SERVI_EMP { get; set; }
        public int CREADOR_TKT { get; set; }
        public short REPORTADOR_TKT { get; set; }
        public string AFECTADO_TKT { get; set; }
        public int PRIORIDAD_TKT { get; set; }
        public byte VALOR_IMPACTO_TKT { get; set; }
        public byte VALOR_URGENCIA_TKT { get; set; }
        public Nullable<decimal> Id_EMPRESA_PROV { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIA> HISTORIA { get; set; }
        public virtual IMPACTO IMPACTO { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        public virtual SERVICIO_EMPRESA SERVICIO_EMPRESA { get; set; }
        public virtual TIPIFICACION TIPIFICACION { get; set; }
        public virtual URGENCIA URGENCIA { get; set; }
    }
}
